#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

e() {
    /Applications/Emacs.app/Contents/MacOS/Emacs $@ 2>&1 > /dev/null &
}

find_port() {
    lsof -i tcp:$@
}

watch_ip() {
    watch -n1 "netstat -an | grep '${1}' | grep EST | awk '{print \$4, \$5, \$6;}' | sort"
}

watch_host() {
    ip=`nslookup ${1} | tail -n2 | head -n1 | awk '{print $2}'`
    watch_ip $ip
}

pg() {
    ps -ef | grep "$1" | grep -v 'grep' | grep "$1"
}

PATH="/Users/jiajzhou/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/Users/jiajzhou/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/Users/jiajzhou/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/Users/jiajzhou/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/Users/jiajzhou/perl5"; export PERL_MM_OPT;

alias ws="cd ~/Workspace"
alias dl="cd ~/Downloads"
alias l="ls -lha"
alias redisstart='sudo launchctl start io.redis.redis-server'
alias redisstop='sudo launchctl stop io.redis.redis-server'
alias ngstart='sudo launchctl start homebrew.mxcl.nginx'
alias ngstop='sudo launchctl stop homebrew.mxcl.nginx'
alias gs="git status"
alias gd="git difftool"
alias gitcheck="git ls-files --error-unmatch"
alias jkserve="bundle exec jekyll serve"
alias ec="emacsclient -nw"
alias er="emacsclient -e '(kill-emacs)' > /dev/null 2>&1; launchctl unload ~/Library/LaunchAgents/gnu.emacs.daemon.plist; launchctl load ~/Library/LaunchAgents/gnu.emacs.daemon.plist"
alias vim="/Applications/MacVim.app/Contents/MacOS/Vim"
alias vi="vim"
alias em="emacs -q -l ~/.emacs.d.clean/init.el"

export HOMEBREW_GITHUB_API_TOKEN="0d0e4b6cdb5fa8e502cd97d9fdb63728f689b091"
export BYOBU_PREFIX=$(brew --prefix)

[ -e ~/.zshrc.local ] && source ~/.zshrc.local

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
setopt clobber
export SDKMAN_DIR="/Users/jiajzhou/.sdkman"
[[ -s "/Users/jiajzhou/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/jiajzhou/.sdkman/bin/sdkman-init.sh"
setopt noclobber
