#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

e() {
    /Applications/Emacs.app/Contents/MacOS/Emacs $@ 2>&1 > /dev/null &
}

find_port() {
    lsof -i tcp:$@
}

watch_ip() {
    watch -n1 "netstat -an | grep '${1}' | grep EST | awk '{print \$4, \$5, \$6;}' | sort"
}

watch_host() {
    ip=`nslookup ${1} | tail -n2 | head -n1 | awk '{print $2}'`
    watch_ip $ip
}

alias ws="cd ~/Workspace"
alias dl="cd ~/Downloads"
alias l="ls -lha"
alias redisstart='sudo launchctl start io.redis.redis-server'
alias redisstop='sudo launchctl stop io.redis.redis-server'
alias ngstart='sudo launchctl start homebrew.mxcl.nginx'
alias ngstop='sudo launchctl stop homebrew.mxcl.nginx'
alias gs="git status"
alias gd="git difftool"
alias gitcheck="git ls-files --error-unmatch"
alias jkserve="bundle exec jekyll serve"
alias ec="emacsclient -nw"
alias er="emacsclient -e '(kill-emacs)' > /dev/null 2>&1; launchctl unload ~/Library/LaunchAgents/gnu.emacs.daemon.plist; launchctl load ~/Library/LaunchAgents/gnu.emacs.daemon.plist"
alias vim="/Applications/MacVim.app/Contents/MacOS/Vim"
alias vi="vim"

[ -e ~/.zshrc.local ] && source ~/.zshrc.local
